// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgUl_zdkSlP1bTVlpF-wjLBO-FebNi-Lo',
    appId: '1:964417947768:web:0e45d6c9c7e35b0e18858d',
    messagingSenderId: '964417947768',
    projectId: 'hello-project-ba6d5',
    authDomain: 'hello-project-ba6d5.firebaseapp.com',
    storageBucket: 'hello-project-ba6d5.appspot.com',
    measurementId: 'G-1XFVNHTNK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPant3voveFmytCgMjM0BdSnR1JkLqJI',
    appId: '1:964417947768:android:b1edae98876646a018858d',
    messagingSenderId: '964417947768',
    projectId: 'hello-project-ba6d5',
    storageBucket: 'hello-project-ba6d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJbh_b5vCYiYtA4M4e4g6EWdknJveVEr4',
    appId: '1:964417947768:ios:922124201fc6f24f18858d',
    messagingSenderId: '964417947768',
    projectId: 'hello-project-ba6d5',
    storageBucket: 'hello-project-ba6d5.appspot.com',
    iosBundleId: 'com.example.getxTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJbh_b5vCYiYtA4M4e4g6EWdknJveVEr4',
    appId: '1:964417947768:ios:922124201fc6f24f18858d',
    messagingSenderId: '964417947768',
    projectId: 'hello-project-ba6d5',
    storageBucket: 'hello-project-ba6d5.appspot.com',
    iosBundleId: 'com.example.getxTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgUl_zdkSlP1bTVlpF-wjLBO-FebNi-Lo',
    appId: '1:964417947768:web:71b9c226db2e4ac718858d',
    messagingSenderId: '964417947768',
    projectId: 'hello-project-ba6d5',
    authDomain: 'hello-project-ba6d5.firebaseapp.com',
    storageBucket: 'hello-project-ba6d5.appspot.com',
    measurementId: 'G-H7WWPJ81XN',
  );

}